version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
#    ports:
#      - '2181:2181'
    expose:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - data-convertor-network
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kakfa-data-convertor
    ports:
     - '9092:9092'
    expose:
      - '9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      - KAFKA_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS:LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      - KAFKA_LISTENERS:LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME:LISTENER_DOCKER_EXTERNAL
#      - KAFKA_CREATE_TOPICS:"orders:1:1"
    networks:
      - data-convertor-network
    depends_on:
      - zookeeper
  mysql-db:
    image: mysql:5.7
    container_name: mysql-data-convertor-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=data-convertor-db
      - MYSQL_USER=data-convertor-db-user
      - MYSQL_PASSWORD=12345678
#    ports:
#      - '3306:3306'
    networks:
      - data-convertor-network
    expose:
     - '3306'
    volumes:
      - data-convertor-db:/var/lib/mysql
  data-producer:
    build:
      # path where docker file has to be present
      context: data-producer
      # name of docker file
      dockerfile: Dockerfile
    # name for newly build image, with tag latest
    image: data-producer:latest
    environment:
      spring.datasource.url: jdbc:mysql://mysql-db:3306/data-convertor-db
      spring.kafka.producer.bootstrap-servers: kafka:9092
    ports:
      - '9001-9010:9000'
    expose:
      - '9001'
    depends_on:
      - mysql-db
      - kafka
    networks:
      - data-convertor-network
  data-consumer:
   build:
     context: data-consumer
     dockerfile: Dockerfile
   image: data-consumer:latest
   environment:
     spring.datasource.url: jdbc:mysql://mysql-db:3306/data-convertor-db
     spring.kafka.consumer.bootstrap-servers: kafka:9092
   ports:
    - '9011-9015:9000'
   expose:
     - '9011'
   depends_on:
     - mysql-db
     - kafka
   networks:
    - data-convertor-network
# Names our volume
volumes:
  data-convertor-db:
networks:
  data-convertor-network:
    driver: bridge