server:
  port: 0

kafka-topic:
  topic-1:
    name: 'operation-topic'
    partition: 5
    replication-factor: 1

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:mysql://localhost:3306/data-convertor-db?useSSL=false
    username: data-convertor-db-user
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update